# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n5WB3ZumJU83eZIqRCO7hd5paagZ8SpS
"""

import pandas as pd
import numpy as np
exam_data={
    'name':['Anastasia','Dima','Katherine','James','Emily','Michael','Mathew','Laura','Kevin','Jonas'],
    'score':[12.5,9,16.5,np.nan,9,20,14.5,np.nan,8,19],
    'attempts':[1,3,2,3,2,3,1,1,2,1],
    'qualify':['yes','yes','yes','no','yes','yes','yes','no','yes','yes'],
}
labels=['a','b','c','d','e','f','g','h','i','j']
df=pd.DataFrame(exam_data,index=labels)
print(df)